#!/bin/bash

MSG_INVALID_DIR_NAME="El nombre del directorio sólo puede contener letras y debe tener de 1 a 15 caracteres. Intente nuevamente:"
MSG_INVALID_INTEGER="Tiene que ingresar un número entero. Intente nuevamente:"
DIR_NAME_REGEX=^[a-zA-Z]{1,15}\(/[a-zA-Z]{1,15}\){0,}$
INTEGER_REGEX=^[0-9]+$
GRUPO=grupo06
CONFDIR="$GRUPO"/conf
BINDIR="$GRUPO"/bin
MAEDIR="$GRUPO"/mae
NOVEDIR="$GRUPO"/novedades
ACEPDIR="$GRUPO"/aceptadas
PROCDIR="$GRUPO"/sospechosas
REPODIR="$GRUPO"/reportes
LOGDIR="$GRUPO"/log
RECHDIR="$GRUPO"/rechazadas
DATASIZE=100
LOGEXT=lg
LOGSIZE=400

LOG_INFO_TYPE=INFO
LOG_ERROR_TYPE=ERROR

function log {
	message=$1
	type=$2
	./GraLog "AFINSTAL" "$message" "$type"
}

function log2 {
	message=$1
	type=$2
	if [ -n $3 ]; then
		echo "$message"
	fi
	./GraLog "AFINSTAL" "$message" "$type"
}

#Chequea que Perl esté instalado
function check_perl {
	perl_version=$(dpkg-query -W perl | sed 's-\(perl\)\([[:blank:]]\)\(.*\)-\3-g')
	if [ ! -z $perl_version ]; then
		#GRABAR EN EL LOG
		echo Perl version: "$perl_version"
		log "Perl version: "$perl_version"" "$LOG_INFO_TYPE"
	else
		#Perl no instalado
		echo Para ejecutar el sistema AFRA-J es necesario contar con Perl 5 o superior.
		log "Para ejecutar el sistema AFRA-J es necesario contar con Perl 5 o superior." "$LOG_INFO_TYPE"
		echo Efectúe su instalación e inténtelo nuevamente.
		log "Efectúe su instalación e inténtelo nuevamente." "$LOG_INFO_TYPE"
		echo Proceso de Instalación Cancelado
		log "Proceso de Instalación Cancelado" "$LOG_INFO_TYPE"
		exit
	fi

}

#Pide al usuario que acepte los términos y condiciones
function terms_and_conditions {
	echo
	echo "***************************************************"
	log "*  Proceso de Instalación de \"AFRA-J\"  *" "$LOG_INFO_TYPE"
	echo \*  Tema J Copyright © Grupo 06 - Segundo Cuatrimestre 2015  \*
	log "*  Tema J Copyright © Grupo 06 - Segundo Cuatrimestre 2015  *" "$LOG_INFO_TYPE"
	echo "***************************************************"
	echo A T E N C I O N: Al instalar UD. expresa aceptar los términos y condiciones del \"ACUERDO DE LICENCIA DE SOFTWARE\" incluido en este paquete.
	log 'A T E N C I O N: Al instalar UD. expresa aceptar los términos y condiciones del "ACUERDO DE LICENCIA DE SOFTWARE" incluido en este paquete.' "$LOG_INFO_TYPE"
	echo Acepta\? Si – No
	log "Acepta? Si – No" "$LOG_INFO_TYPE"
	read terms_choice

	while [ "$terms_choice" != Si ] && [ "$terms_choice" != No ];
	do
		echo Debe ingresar Si o No:
		read terms_choice
	done
	log "$terms_choice" "$LOG_INFO_TYPE"
	if [ "$terms_choice" == No ]; then
		echo Instalación cancelada.
		log "Instalación cancelada." "$LOG_INFO_TYPE"
		exit
	fi
}


function choose_dir {
	# $1 Variable de directorio a settear.
	# $2 Mensaje pidiendo ingreso del path.
	# $3 Mensaje a mostrar una vez ingresado correctamente el path.
	
	log2 "$2" "$LOG_INFO_TYPE" "s"

	read input_dir
	if [ ! -z "$input_dir" ]; then
		while ! [[ $input_dir =~ $DIR_NAME_REGEX ]];
		do
			echo "$MSG_INVALID_DIR_NAME"
			read input_dir
			if [ -z "$input_dir" ]; then
				log2 "$3 ${!1}" "$LOG_INFO_TYPE" "s"
				echo
				return
			fi
		done
		eval $1="$GRUPO"/"$input_dir"
	fi
	
	log2 "$3 ${!1}" "$LOG_INFO_TYPE" "s"
	echo
}

#Ingreso de espacio mínimo libre para la recepción de archivos de llamadas
function choose_nove_dir_space {
	espacio_disponible=$(df -h -B M --output='avail' grupo06 | tail -1 | sed 's-\([0-9]*\)\(M\)-\1-g')

	echo Defina espacio mínimo libre para la recepción de archivos de llamadas en Mbytes \("$DATASIZE"\):
	log "Defina espacio mínimo libre para la recepción de archivos de llamadas en Mbytes ("$DATASIZE"):" "$LOG_INFO_TYPE"
	read data_size
	if [ ! -z "$data_size" ]; then
		while [[ ! $data_size =~ $INTEGER_REGEX ]];
		do
			echo "$MSG_INVALID_INTEGER"
			read data_size
			if [ -z "$data_size" ]; then
				echo El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb
				log "El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb" "$LOG_INFO_TYPE"
				echo
				return
			fi
		done
	else
		echo El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb
		log "El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb" "$LOG_INFO_TYPE"
		echo
		return
	fi

	while (( espacio_disponible < data_size ));
	do
		echo Insuficiente espacio en disco.
		log "Insuficiente espacio en disco." "$LOG_INFO_TYPE"
		echo Espacio disponible: "$espacio_disponible" Mb.
		log "Espacio disponible: "$espacio_disponible" Mb." "$LOG_INFO_TYPE"
		echo Espacio requerido "$data_size" Mb.
		log "Espacio requerido "$data_size" Mb." "$LOG_INFO_TYPE"
		echo Inténtelo nuevamente:
		log "Inténtelo nuevamente:" "$LOG_INFO_TYPE"

		read data_size
		if [ ! -z "$data_size" ]; then
			while [[ ! $data_size =~ $INTEGER_REGEX ]];
			do
				echo "$MSG_INVALID_INTEGER"
				read data_size
				if [ -z "$data_size" ]; then
					echo El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb
					log "El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb" "$LOG_INFO_TYPE"
					echo
					return
				fi
			done
		else
			echo El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb
			log "El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb" "$LOG_INFO_TYPE"
			echo
			return
		fi
	done

	DATASIZE="$data_size"
	echo El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb
	log "El espacio mínimo libre para la recepción de archivos será "$DATASIZE" Mb" "$LOG_INFO_TYPE"
	echo
}

#Ingreso de nombre de extensión de archivos de log
function choose_log_extension_name {
	echo Defina el nombre para la extensión de los archivos de log \("$LOGEXT"\):
	log "Defina el nombre para la extensión de los archivos de log ("$LOGEXT"):" "$LOG_INFO_TYPE"
	read log_ext
	if [ -z "$log_ext" ]; then
		echo El nombre para la extensión de los archivos de log será "$LOGEXT"
		log "El nombre para la extensión de los archivos de log será "$LOGEXT"" "$LOG_INFO_TYPE"
		echo
		return
	fi

	while ! [[ $log_ext =~ ^[a-zA-Z]{2,5}$ ]];
	do
		echo La extensión debe estar compuesta solamente por letras y debe tener de 2 a 5 caracteres.
		echo Defina el nombre para la extensión de los archivos de log \("$LOGEXT"\):
		read log_ext
		if [ -z "$log_ext" ]; then
			echo El nombre para la extensión de los archivos de log será "$LOGEXT"
			log "El nombre para la extensión de los archivos de log será "$LOGEXT"" "$LOG_INFO_TYPE"
			echo
			return
		fi
	done

	LOGEXT="$log_ext"
	echo El nombre para la extensión de los archivos de log será "$LOGEXT"
	log "El nombre para la extensión de los archivos de log será "$LOGEXT"" "$LOG_INFO_TYPE"
	echo
}

#Ingreso de tamaño máximo para archivos de log
function choose_log_file_max_size {
	echo Defina el tamaño máximo para cada archivo de log en Kbytes \("$LOGSIZE"\):
	log "Defina el tamaño máximo para cada archivo de log en Kbytes ("$LOGSIZE"):" "$LOG_INFO_TYPE"
	read log_size
	if [ -z "$log_size" ]; then
		echo El tamaño máximo para cada archivo de log será "$LOGSIZE" Kb
		log "El tamaño máximo para cada archivo de log será "$LOGSIZE" Kb" "$LOG_INFO_TYPE"
		echo
		return
	fi

	while [[ ! $log_size =~ $INTEGER_REGEX ]];
	do
		echo "$MSG_INVALID_INTEGER"
		read log_size
		if [ -z "$log_size" ]; then
			echo El tamaño máximo para cada archivo de log será "$LOGSIZE" Kb
			log "El tamaño máximo para cada archivo de log será "$LOGSIZE" Kb" "$LOG_INFO_TYPE"
			echo
		return
	fi
	done

	LOGSIZE="$log_size"
	echo El tamaño máximo para cada archivo de log será "$LOGSIZE" Kb
	log "El tamaño máximo para cada archivo de log será "$LOGSIZE" Kb" "$LOG_INFO_TYPE"
	echo
}

function choose_vars_values {
	#choose_bin_dir
	choose_dir BINDIR "Defina el directorio de instalación de los ejecutables ($BINDIR):" "El directorio de ejecutables será"
	#choose_mae_dir
	choose_dir MAEDIR "Defina el directorio para maestros y tablas ($MAEDIR):" "El directorio para maestros y tablas será"
	#choose_nove_dir
	choose_dir NOVEDIR "Defina el directorio de recepción de archivos de llamadas ($NOVEDIR):" "El directorio de recepción de archivos de llamadas será"
	choose_nove_dir_space
	#choose_acep_dir
	choose_dir ACEPDIR "Defina el directorio de grabación de los archivos de llamadas aceptadas ($ACEPDIR):" "El directorio de grabación de los archivos de llamadas aceptadas será"
	#choose_proc_dir
	choose_dir PROCDIR "Defina el directorio de grabación de los registros de llamadas sospechosas ($PROCDIR):" "El directorio de grabación de los registros de llamadas sospechosas será"
	#choose_repo_dir
	choose_dir REPODIR "Defina el directorio de grabación de los reportes ($REPODIR):" "El directorio de grabación de los reportes será"
	#choose_log_dir
	choose_dir LOGDIR "Defina el directorio para los archivos de log ($LOGDIR):" "El directorio para los archivos de log será"
	choose_log_extension_name
	choose_log_file_max_size
	#choose_rech_dir
	choose_dir RECHDIR "Defina el directorio de grabación de archivos rechazados ($RECHDIR):" "El directorio de grabación de archivos rechazados será"
}

#Muestra el nombre de las variables de configuración
function show_vars_values {
	echo Directorio de Ejecutables: "$BINDIR"
	log "Directorio de Ejecutables: "$BINDIR"" "$LOG_INFO_TYPE"
	echo Directorio de Maestros y Tablas: "$MAEDIR"
	log "Directorio de Maestros y Tablas: "$MAEDIR"" "$LOG_INFO_TYPE"
	echo Directorio de recepción de archivos y llamadas: "$NOVEDIR"
	log "Directorio de recepción de archivos y llamadas: "$NOVEDIR"" "$LOG_INFO_TYPE"
	echo Espacio mínimo libre para arribos: "$DATASIZE" Mb
	log "Espacio mínimo libre para arribos: "$DATASIZE" Mb" "$LOG_INFO_TYPE"
	echo Directorio de Archivos de llamadas Aceptados: "$ACEPDIR"
	log "Directorio de Archivos de llamadas Aceptados: "$ACEPDIR"" "$LOG_INFO_TYPE"
	echo Directorio de Archivos de llamadas Sospechosas: "$PROCDIR"
	log "Directorio de Archivos de llamadas Sospechosas: "$PROCDIR"" "$LOG_INFO_TYPE"
	echo Directorio de Archivos de Reportes de llamadas: "$REPODIR"
	log "Directorio de Archivos de Reportes de llamadas: "$REPODIR"" "$LOG_INFO_TYPE"
	echo Directorio de Archivos de Log: "$LOGDIR"
	log "Directorio de Archivos de Log: "$LOGDIR"" "$LOG_INFO_TYPE"
	echo Extensión para los archivos de log: "$LOGEXT"
	log "Extensión para los archivos de log: "$LOGEXT"" "$LOG_INFO_TYPE"
	echo Tamaño máximo para los archivos de log: "$LOGSIZE" Kb
	log "Tamaño máximo para los archivos de log: "$LOGSIZE" Kb" "$LOG_INFO_TYPE"
	echo Directorio de Archivos Rechazados: "$RECHDIR"
	log "Directorio de Archivos Rechazados: "$RECHDIR"" "$LOG_INFO_TYPE"
}

function continue_install {
	show_vars_values
	echo Estado de la instalación: LISTA
	log "Estado de la instalación: LISTA" "$LOG_INFO_TYPE"
	#Continuar instalación?
	echo Desea continuar con la instalación\? \(Si – No\)
	log "Desea continuar con la instalación? (Si – No)" "$LOG_INFO_TYPE"
	read continue_choice
	while [ "$continue_choice" != Si ] && [ "$continue_choice" != No ];
	do
		echo Debe ingresar Si o No:
		read continue_choice
	done
	log "$continue_choice" "$LOG_INFO_TYPE"
	if [ "$continue_choice" == Si ]; then
		return
	fi

	while [ "$continue_choice" == No ]; 
	do
		choose_vars_values
		show_vars_values
		echo Estado de la instalación: LISTA
		log "Estado de la instalación: LISTA" "$LOG_INFO_TYPE"
		#Continuar instalación?
		echo Desea continuar con la instalación\? \(Si – No\)
		log "Desea continuar con la instalación? (Si – No)" "$LOG_INFO_TYPE"
		read continue_choice
		while [ "$continue_choice" != Si ] && [ "$continue_choice" != No ];
		do
			echo Debe ingresar Si o No:
			read continue_choice
		done
		log "$continue_choice" "$LOG_INFO_TYPE"
		if [ "$continue_choice" == Si ]; then
			return
		fi
	done	
}

function confirm_install {
	echo Iniciando Instalación. Esta Ud. seguro\? \(Si - No\)
	log "Iniciando Instalación. Esta Ud. seguro? (Si - No)" "$LOG_INFO_TYPE"
	read install_choice
	while [ "$install_choice" != Si ] && [ "$install_choice" != No ];
	do
		echo Debe ingresar Si o No:
		read install_choice
	done
	log "$install_choice" "$LOG_INFO_TYPE"
	if [ "$continue_choice" == No ]; then
		echo Instalación cancelada.
		log "Instalación cancelada." "$LOG_INFO_TYPE"
		exit
	fi	
}

function create_dirs {
	mkdir -p "$BINDIR"
	mkdir -p "$MAEDIR"
	mkdir -p "$NOVEDIR"
	mkdir -p "$ACEPDIR"
	mkdir -p "$PROCDIR"
	mkdir -p "$REPODIR"
	mkdir -p "$LOGDIR"
	mkdir -p "$RECHDIR"
	echo
}

function copy_binaries {
	cp AFINI "$BINDIR"/AFINI
	cp AFREC "$BINDIR"/AFREC
	cp AFUMB "$BINDIR"/AFUMB
	cp GraLog "$BINDIR"/GraLog
	cp Arrancar "$BINDIR"/Arrancar
	cp Detener "$BINDIR"/Detener
	cp MoverA "$BINDIR"/MoverA	
	chmod -R +r+w+x "$BINDIR"
}

function copy_tables {
	cp ../../archivos/CdP.csv "$MAEDIR"/CdP.mae	
	cp ../../archivos/CdA.csv "$MAEDIR"/CdA.mae	
	cp ../../archivos/centrales.csv "$MAEDIR"/CdC.mae	
	cp ../../archivos/agentes.csv "$MAEDIR"/agentes.mae
	cp ../../archivos/umbrales.csv "$MAEDIR"/umbral.tab
	touch "$MAEDIR"/tllama.tab
	> "$MAEDIR"/tllama.tab
	#Doy permisos a todos a todo el directorio
	chmod -R +r+w "$MAEDIR"
	echo DISCADO DIRECTO INTERNACIONAL\;DDI >> "$MAEDIR"/tllama.tab
	echo DISCADO DIRECTO NACIONAL\;DDN >> "$MAEDIR"/tllama.tab
	echo LOCAL\;LOC >> "$MAEDIR"/tllama.tab
}

function update_config_file {
	echo Actualizando la configuración del sistema
	log "Actualizando la configuración del sistema" "$LOG_INFO_TYPE"
	touch "$CONFDIR"/AFINSTAL.cnfg
	#De esta manera borro lo que haya:
	> "$CONFDIR"/AFINSTAL.cnfg
	#Doy permisos a todos a todo el directorio de configuración
	chmod -R +r+w "$CONFDIR"
	#Copio los registros al archivo de configuración
	echo GRUPO=$(pwd)/"$GRUPO"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo CONFDIR=$(pwd)/"$CONFDIR"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo BINDIR=$(pwd)/"$BINDIR"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo MAEDIR=$(pwd)/"$MAEDIR"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo NOVEDIR=$(pwd)/"$NOVEDIR"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo ACEPDIR=$(pwd)/"$ACEPDIR"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo PROCDIR=$(pwd)/"$PROCDIR"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo REPODIR=$(pwd)/"$REPODIR"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo LOGDIR=$(pwd)/"$LOGDIR"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo RECHDIR=$(pwd)/"$RECHDIR"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo DATASIZE="$DATASIZE"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo LOGEXT="$LOGEXT"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
	echo LOGSIZE="$LOGSIZE"="$USER"=$(date) >> "$CONFDIR"/AFINSTAL.cnfg
}

function do_install {
	echo Creando Estructuras de directorio. . . .
	log "Actualizando la configuración del sistema" "$LOG_INFO_TYPE"
	echo "$BINDIR"
	log "$BINDIR" "$LOG_INFO_TYPE"
	echo "$MAEDIR"
	log "$MAEDIR" "$LOG_INFO_TYPE"
	echo "$NOVEDIR"
	log "$NOVEDIR" "$LOG_INFO_TYPE"
	echo "$ACEPDIR"
	log "$ACEPDIR" "$LOG_INFO_TYPE"
	echo "$PROCDIR"
	log "$PROCDIR" "$LOG_INFO_TYPE"
	echo "$REPODIR"
	log "$REPODIR" "$LOG_INFO_TYPE"
	echo "$LOGDIR"
	log "$LOGDIR" "$LOG_INFO_TYPE"
	echo "$RECHDIR"
	log "$RECHDIR" "$LOG_INFO_TYPE"
	create_dirs
	echo Instalando Programas y Funciones
	log "Instalando Programas y Funciones" "$LOG_INFO_TYPE"
	copy_binaries
	echo Instalando Archivos Maestros y Tablas
	log "Instalando Archivos Maestros y Tablas" "$LOG_INFO_TYPE"
	copy_tables
	update_config_file
	echo Instalación CONCLUIDA.
	log "Instalación CONCLUIDA." "$LOG_INFO_TYPE"
}

#Se encarga de completar la instalacion de ser necesario
function complete_install {
	if [ ! -f "$CONFDIR"/AFINSTAL.cnfg ]; then
    	#AFRAJ NO esta instalado
    	return
	fi

	declare -a missing_dirs
	declare -a missing_files
	mae_filenames=(CdP.mae CdA.mae CdC.mae agentes.mae umbral.tab tllama.tab)
	bin_filenames=(AFINI AFREC AFUMB GraLog Arrancar Detener MoverA)
	
	index_dirs=0
	index_files=0

	#CONFDIR
	conf_path=$(grep CONFDIR "$CONFDIR"/AFINSTAL.cnfg | sed 's-^\([^=]*\)=\([^=]*\)=\(.*\)$-\2-g')
	if [ ! -d "$conf_path" ]; then
		missing_dirs[index_dirs]="$conf_path"
		((index_dirs++))
	fi

	#MAEDIR
	mae_path=$(grep MAEDIR "$CONFDIR"/AFINSTAL.cnfg | sed 's-^\([^=]*\)=\([^=]*\)=\(.*\)$-\2-g')
	if [ ! -d "$mae_path" ]; then
		missing_dirs[index_dirs]="$mae_path"
		((index_dirs++))
	fi
	for mae_file in "${mae_filenames[@]}"
	do
		if [ ! -f "$mae_path"/"$mae_file" ]; then
			missing_files[index_files]="$mae_path"/"$mae_file"
			((index_files++))
		fi
	done

	#BINDIR
	bin_path=$(grep BINDIR "$CONFDIR"/AFINSTAL.cnfg | sed 's-^\([^=]*\)=\([^=]*\)=\(.*\)$-\2-g')
	if [ ! -d "$bin_path" ]; then
		missing_dirs[index_dirs]="$bin_path"
		((index_dirs++))
	fi
	for bin_file in "${bin_filenames[@]}"
	do
		if [ ! -f "$bin_path"/"$bin_file" ]; then
			missing_files[index_files]="$bin_path"/"$bin_file"
			((index_files++))
		fi
	done

	#NOVEDIR
	nove_path=$(grep NOVEDIR "$CONFDIR"/AFINSTAL.cnfg | sed 's-^\([^=]*\)=\([^=]*\)=\(.*\)$-\2-g')
	if [ ! -d "$nove_path" ]; then
		missing_dirs[index_dirs]="$nove_path"
		((index_dirs++))
	fi

	#ACEPDIR
	acep_path=$(grep ACEPDIR "$CONFDIR"/AFINSTAL.cnfg | sed 's-^\([^=]*\)=\([^=]*\)=\(.*\)$-\2-g')
	if [ ! -d "$acep_path" ]; then
		missing_dirs[index_dirs]="$acep_path"
		((index_dirs++))
	fi

	#PROCDIR
	proc_path=$(grep PROCDIR "$CONFDIR"/AFINSTAL.cnfg | sed 's-^\([^=]*\)=\([^=]*\)=\(.*\)$-\2-g')
	if [ ! -d "$proc_path" ]; then
		missing_dirs[index_dirs]="$proc_path"
		((index_dirs++))
	fi

	#REPODIR
	repo_path=$(grep REPODIR "$CONFDIR"/AFINSTAL.cnfg | sed 's-^\([^=]*\)=\([^=]*\)=\(.*\)$-\2-g')
	if [ ! -d "$repo_path" ]; then
		missing_dirs[index_dirs]="$repo_path"
		((index_dirs++))
	fi

	#LOGDIR
	log_path=$(grep LOGDIR "$CONFDIR"/AFINSTAL.cnfg | sed 's-^\([^=]*\)=\([^=]*\)=\(.*\)$-\2-g')
	if [ ! -d "$log_path" ]; then
		missing_dirs[index_dirs]="$log_path"
		((index_dirs++))
	fi

	#RECHDIR
	rech_path=$(grep RECHDIR "$CONFDIR"/AFINSTAL.cnfg | sed 's-^\([^=]*\)=\([^=]*\)=\(.*\)$-\2-g')
	if [ ! -d "$rech_path" ]; then
		missing_dirs[index_dirs]="$rech_path"
		((index_dirs++))
	fi

	#Esto tambien hay que loguearlo:
	echo Directorio de configuración: "$conf_path"
	log 'Directorio de configuración: "$conf_path"' "$LOG_INFO_TYPE"
	echo $(ls -m "$conf_path")
	log "$(ls -m "$conf_path")" "$LOG_INFO_TYPE"
	echo Directorio de ejecutables: "$bin_path"
	log 'Directorio de ejecutables: "$bin_path"' "$LOG_INFO_TYPE"
	echo $(ls -m "$bin_path")
	log "$(ls -m "$bin_path")" "$LOG_INFO_TYPE"
	echo Directorio de maestros y tablas: "$mae_path"
	log 'Directorio de maestros y tablas: "$mae_path"' "$LOG_INFO_TYPE"
	echo $(ls -m "$mae_path")
	log "$(ls -m "$mae_path")" "$LOG_INFO_TYPE"
	echo Directorio de recepción de archivos de llamadas: "$nove_path"
	log 'Directorio de recepción de archivos de llamadas: "$nove_path"' "$LOG_INFO_TYPE"
	echo Directorio de archivos de llamadas aceptadas: "$acep_path"
	log 'Directorio de archivos de llamadas aceptadas: "$acep_path"' "$LOG_INFO_TYPE"
	echo Directorio de archivos de llamadas sospechosas: "$proc_path"
	log 'Directorio de archivos de llamadas sospechosas: "$proc_path"' "$LOG_INFO_TYPE"
	echo Directorio de archivos de reportes de llamadas: "$repo_path"
	log 'Directorio de archivos de reportes de llamadas: "$repo_path"' "$LOG_INFO_TYPE"
	echo Directorio de archivos de log: "$log_path"
	log 'Directorio de archivos de log: "$log_path"' "$LOG_INFO_TYPE"
	echo Directorio de archivos rechazados: "$rech_path"
	log 'Directorio de archivos rechazados: "$rech_path"' "$LOG_INFO_TYPE"

	if [ ${#missing_dirs[@]} == 0 ] && [ ${#missing_files[@]} == 0 ]; then
		echo Estado de la instalación: COMPLETA
		log "Estado de la instalación: COMPLETA" "$LOG_INFO_TYPE"
		echo Proceso de Instalación Finalizado
		log "Proceso de Instalación Finalizado" "$LOG_INFO_TYPE"
		exit
	fi

	echo Directorios faltantes:
	log "Directorios faltantes:" "$LOG_INFO_TYPE"
	echo "${missing_dirs[*]}"
	log "${missing_dirs[*]}" "$LOG_INFO_TYPE"
	echo Archivos faltantes:
	log "Archivos faltantes:" "$LOG_INFO_TYPE"
	echo "${missing_files[*]}"
	log "${missing_files[*]}" "$LOG_INFO_TYPE"

	echo Desea completar la instalación\? \(Si – No\)
	log "Desea completar la instalación? (Si – No)" "$LOG_INFO_TYPE"
	read complete_choice
	while [ "$complete_choice" != Si ] && [ "$complete_choice" != No ];
	do
		echo Debe ingresar Si o No:
		read complete_choice
	done
	if [ "$complete_choice" == No ]; then
		echo Instalación cancelada.
		log "Instalación cancelada." "$LOG_INFO_TYPE"
		exit
	fi

	#Instalo de nuevo
	BINDIR=$bin_path
	MAEDIR=$mae_path
	NOVEDIR=$nove_path
	ACEPDIR=$acep_path
	PROCDIR=$proc_path
	REPODIR=$repo_path
	LOGDIR=$log_path
	RECHDIR=$rech_path

	create_dirs
	copy_binaries
	copy_tables

	#Esto tambien hay que loguearlo:
	echo Directorio de configuración: "$conf_path"
	log "Directorio de configuración: "$conf_path"" "$LOG_INFO_TYPE"
	echo $(ls -m "$conf_path")
	log "$(ls -m "$conf_path")" "$LOG_INFO_TYPE"
	echo Directorio de ejecutables: "$bin_path"
	log "Directorio de ejecutables: "$bin_path"" "$LOG_INFO_TYPE"
	echo $(ls -m "$bin_path")
	log "$(ls -m "$bin_path")" "$LOG_INFO_TYPE"
	echo Directorio de maestros y tablas: "$mae_path"
	log "Directorio de maestros y tablas: "$mae_path"" "$LOG_INFO_TYPE"
	echo $(ls -m "$mae_path")
	log "$(ls -m "$mae_path")" "$LOG_INFO_TYPE"
	echo Directorio de recepción de archivos de llamadas: "$nove_path"
	log "Directorio de recepción de archivos de llamadas: "$nove_path"" "$LOG_INFO_TYPE"
	echo Directorio de archivos de llamadas aceptadas: "$acep_path"
	log "Directorio de archivos de llamadas aceptadas: "$acep_path"" "$LOG_INFO_TYPE"
	echo Directorio de archivos de llamadas sospechosas: "$proc_path"
	log "Directorio de archivos de llamadas sospechosas: "$proc_path"" "$LOG_INFO_TYPE"
	echo Directorio de archivos de reportes de llamadas: "$repo_path"
	log "Directorio de archivos de reportes de llamadas: "$repo_path"" "$LOG_INFO_TYPE"
	echo Directorio de archivos de log: "$log_path"
	log "Directorio de archivos de log: "$log_path"" "$LOG_INFO_TYPE"
	echo Directorio de archivos rechazados: "$rech_path"
	log "Directorio de archivos rechazados: "$rech_path"" "$LOG_INFO_TYPE"
	echo Estado de la instalación: COMPLETA
	log "Estado de la instalación: COMPLETA" "$LOG_INFO_TYPE"
	echo Proceso de Instalación Finalizado
	log "Proceso de Instalación Finalizado" "$LOG_INFO_TYPE"
	exit
}

#Completar instalacion si es necesario
complete_install
#Chequeo de Perl
check_perl
#Términos y condiciones
terms_and_conditions
#Ingreso de valores de variables de configuración
choose_vars_values
continue_install
#Confirmar instalación
confirm_install
#Instalación propiamente dicha
do_install
