#!/bin/bash

source util.sh
source validadorArchivos.sh

#funcion de logueo
function log {
	message=$1
	type=$2
	echo "$message" "$type"
	./GraLog AFREC "$message" "$type"
}

# parametros 
# $1 nombre de archivo
# $2 resultado validación de archivo
function logRechazados {
	case "$2" in
		1) motivoRechazo="El tipo de archivo es invalido" ;;
		2) motivoRechazo="La fecha del archivo es invalida" ;;
		3) motivoRechazo="La fecha esta fuera del rango preestablecido" ;;
		4) motivoRechazo="La central es inexistente" ;;
	esac
		
	log "Archivo $1 rechazado. $motivoRechazo." "INFO"
}


DORMIR_DEMONIO=10

ciclo=1

while [ 0 ]
do
	log "Ejecutando ciclo nro. $ciclo." "INFO"
	
	for i in `ls "$NOVEDIR"`
	do
		rutaArchivo="$NOVEDIR/$i"
		validarRegistroLlamados $rutaArchivo
		resultado="$?"
		log "Resultado validacion: $resultado"
		if [ $resultado -eq 0 ]
		then
			./MoverA "$NOVEDIR/$i" "$ACEPDIR/"
			log "Archivo $i aceptado." "INFO"
		else 
			./MoverA "$NOVEDIR/$i" "$RECHDIR/"
			logRechazados $i $resultado
		fi
	done
	
	cantidadAceptados=`ls -1 "$ACEPDIR" | wc -l`
	
	if [ $cantidadAceptados != 0 ]
	then
		estaEjecutandose AFUMB
			
		if [ $? = 0 ]
		then
			pid=`pgrep AFUMB`
			log "AFUMB aún corriendo pid $pid. Invocación pospuesta para el siguiente ciclo." "INFO"
		else
			./AFUMB &
			log "AFUMB corriendo bajo el no.: $!" "INFO"
		fi
	fi
	
	sleep $DORMIR_DEMONIO
	# incremento contador de ciclos de ejecución.
	((ciclo+=1))

done
