#!/bin/bash

# Detener - detiene el demonio (AFREC)

afrecPid=`pgrep AFREC`
if [ $? -eq 0 ]; then
    #mata al demonio
    kill -9 $afrecPid
    echo "Demonio detenido."
else
    echo "El demonio no estaba ejecutandose."
    exit 1
fi
exit 0
