#!/bin/bash

# Detener - detiene el demonio (AFUMB)

afumbPid=`pgrep AFUMB`
if [ $? -eq 0 ]; then
    #mata al demonio
    kill -9 $afumbPid
    echo "Demonio detenido."
else
    echo "El demonio no estaba ejecutandose."
    exit 1
fi
exit 0
