#!/bin/bash

#funcion que imprime el correcto uso de la herramienta
function printUsage {
	echo "wrong usage"
	echo "usage:"
	echo "GraLog <command name> <message> <type>"
	echo "type can be:"
	echo "INFO informative"
	echo "WAR warning"
	echo "ERROR error"
	
}

#asegura que tenga los tres parametros requeridos
if [ $# -ne 3 ]
then
	printUsage
	exit 1
fi

#asegura que el tipo del mensaje este entre los mensajes soportados
if [ $3 != "INFO" ] && [ $3 != "WAR" ] && [ $3 != "ERROR" ]
then
	printUsage
	exit 1
fi

## TODO: sacar estas variables. se deben tomar del entorno
logDir=
logExt=".lg"


#path de la carpeta de logueo
logPath="$grupo/comandos/log/"
message=$2
sizeLimit=1048576
filename="$1.$logExt"
file="$logPath$filename"
msgType=$3
date=$(date)
login=$(whoami)

#escribe en el archivo
echo "$date-$login-$1-$msgType-$message" >> "$file"

#obtiene el tamanio del archivo
filesize=$(stat -c%s "$file")

if [ $filesize -gt $sizeLimit ]
then
	echo "log $filename excedido."
fi

exit 0
